### PR TITLE
refactor: remove tokens redundant after CSS rewrite

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

As part of the CSS rewrite some of the tokens have become redundant.

`gcds-link` was integrated into the following components:
- `gcds-breadcrumbs`
- `gcds-card`
- `gcds-footer`
- `gcds-lang-toggle`

`gcds-text` was integrated into the following components:
- `gcds-card`
- `gcds-date-modified`
- `gcds-error-message`
- `gcds-hint`

`gcds-heading` was integrated into the following components:
- `gcds-error-summary`
- `gcds-stepper`

Note: This PR shouldn't be merged until the CSS rewrite changes are published and the component tokens in Figma are updated. I will keep it in draft mode for now.

### CODE REVIEW

**Comment by adorayi** [comment]
Need a touchpoint with Design before merging this PR.

**Comment by melaniebmn** [comment]
@ethanWallace can you confirm that we won't be using the `--gcds-card-hover-title-text-decoration-thickness` token for the card 2.0 design anymore? I checked your draft PR and it looks like that is the only token that can be removed.

**Review by daine — APPROVED** [review]
LGTM, we can wait for ethan to confirm usage of that token

**Comment by ethanWallace** [comment]
> @ethanWallace can you confirm that we won't be using the `--gcds-card-hover-title-text-decoration-thickness` token for the card 2.0 design anymore? I checked your draft PR and it looks like that is the only token that can be removed.

I can confirm that token is no longer being used.

**Comment by melaniebmn** [comment]
@ethanWallace @daine I removed the unused card token, PR should be good to go.

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Pull request merged**
