### PR TITLE
Token restructure

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Complete token restructure for the typography tokens.
The implementation is based on the whitespace requirements doc and the resources that are linked in there.

### CODE REVIEW

**Comment by JoshBeveridge** [comment]
Looks great to me! I mentioned in Slack, but are there any concerns about using % over decimal values for the line heights? Do they behave the exact same way?

**Review by JoshBeveridge — APPROVED** [review]
Looks great to me! I mentioned in Slack, but are there any concerns about using % over decimal values for the line heights? Do they behave the exact same way?

**Review by ethanWallace — APPROVED** [review]
LGTM

**Comment by melaniebmn** [comment]
> Looks great to me! I mentioned in Slack, but are there any concerns about using % over decimal values for the line heights? Do they behave the exact same way?

Posting slack answer here: Decimals don't work in Figma unless its pixels, so I used % since they work in Figma + web.

**Pull request merged**
