### PR TITLE
Add focus box-shadow to multiple components

### PR DESCRIPTION
**Pull request by ethanWallace**
# Summary | Résumé

Add a box-shadow to multiple components to have consistent styling. Based on decision from Dev/Design sync on August 1st.

Updated component tokes:
- Button
- Checkbox
- Input
- Radio
- Pagination
- Select
- Textarea

### CODE REVIEW

**Review by melaniebmn — APPROVED** [review]
LGTM

**Review by melaniebmn — CHANGES_REQUESTED** [review]
Actually, revoking my approval :D Can you update the changelog please and notify @nchoquet?

**Review by daine — APPROVED** [review]
LGTM, thanks for updating the version!

**Review by melaniebmn — APPROVED** [review]
LGTM

**Pull request merged**
