### PR TITLE
Spacing scale 24

### PR DESCRIPTION
**Pull request by amazingphilippe**
# Summary | Résumé

Spacing scale changes:
- lower values are now linear
- Adding 150, 250, 450 and 550
- Changed from 26px base to 24px base for nicer numbers. 
- Added a transform for spacing values in the figma tokens. Figma interprets the font base to be 16px, and we want 20px.

### CODE REVIEW

**Comment by melaniebmn** [comment]
Hey @amazingphilippe, apologies if I misunderstood this conversation during the tokens meeting on Monday, but unless using rem creates problems in Figma, we should stick to rem units for Figma as well. We consciously made the decision to use rem in web & Figma to keep consistent units between design & development as it's part of a shared language between both.

Happy to have a discussion about this if you want :)

**Comment by amazingphilippe** [comment]
> using rem creates problems in Figma

I found that it does!

Figma converts rem units into pixel units when we apply them through the token plugin. It does the conversion using a 16px font scale. We have a 20 px font scale, so its easier for us to convert the spacing into px to avoid any confusion.

From a dev perspective, px units in figma will match the "computed values" when inspecting a page. 

From a designer perspective, Figma doesn't support rem, so using pixel spacing values makes sense.

**Review by melaniebmn — APPROVED** [review]
LGTM

**Review by melaniebmn — APPROVED** [review]
LGTM

**Pull request merged**
